export default {
    "ApprovalProcess": {
        "title": "Approval Flow",
        "processName": "Process Designation:",
        "approver": "Actual Approver:",
        "candidate": "Approver:",
        "operator": "Operator:",
        "status": "Approval Status:",
        "opinions": "Approval Comment:",
        "CCList": "Copy List:",
        "time": "Approval Time:",
        "reason": "Remark:",
        "noData": "No workflow for this transaction",
        "skipped": "Skipped",
        "submitter": "{0} submitted application",
        "outcome": {
            "Y": "Passed",
            "N": "Rejected"
        },
        "approvalStatus": {
            "STARTED": "Pending Approval",
            "COMPLETED": "Approved",
            "CANCELLED": "Cancelled"
        }
    },
    "RevisionComments": {
        "title": "Revised Comment"
    },
    "AttendanceApplyPage": {
        "holiday": "Leave Application",
        "overtime": "OT Application",
        "cancelledLeave": "Leave Withdrawal Application"
    },
    "CompensationMode": {
        "TIMEOFF": "Compensation Leave",
        "PAYROLL": "Compensation Salary",
        "ALL": "Compensation Leave & Salary"
    },
    "FormulaMode": {
        "DAYS": "Daily",
        "HOURS": "Hourly"
    },
    "onlyBasicSalary": {
        "true": "Monthly",
        "false": "Monthly Salary"
    },
    "OvertimeFormListPage": {
        "title": "OT Application",
        "submitApplication": "Submit",
        "approveApplication": "Review",
        "editing": "Editing",
        "submitted": "Submitted",
        "completed": "Approved",
        "carbonCopy": "Copy",
        "processing": "Handling",
        "processed": "Proceeded",
        "billCode": "Number:",
        "department": "Department:",
        "employee": "Staff:",
        "totalHours": "Total Duration:",
        "businessType": "Business Type:",
        "attdPeriod": "Duty Roster:",
        "originAttdPeriod": "原有更期：",
        "reason": "OT Reason:",
        "status": "Status:",
        "revoke": "Retrieve",
        "rescind": "Withdraw",
        "edit": "Edit",
        "delete": "Delete",
        "confirmRevoke": "Confirm to retrieve?",
        "confirmRescind": "Confirm to withdraw?",
        "confirmDelete": "Confirm to delete?",
        "revokeSuccess": "Succeed to retrieve",
        "rescindSuccess": "Succeed to withdraw",
        "deleteSuccess": "Succeed to delete",
        "followUp": "Review",
        "resolve": "Approved",
        "reject": "Disapproved",
        "confirmResolve": "Confirm to approve?",
        "confirmReject": "Confirm to disapprove?",
        "temporarily": "Temporarly not to proceed",
        "approveNote": "Remark",
        lastttdPeriod: "最新更期：",
    },
    "OvertimeFormPage": {
        "title": "OT Application",
        "overtimeFormDetail": "OT Application Details",
        "department": "Department",
        "overtimeType": "OT Type",
        "businessType": "Business Type",
        "totalHours": "Total Duration",
        "reason": "OT Reason",
        "workOrderNumber": "Work Order No/Name",
        "accessRecordDate": "Attendance Date",
        "fromTime": "Start Time",
        "toTime": "End Time",
        "hours": "OT Hours",
        "compensation": "Compensation Amount",
        "overtimeTypeRule": "OT Rules:",
        "compensationMode": "Compensation Type",
        "externalCode": "Reference No",
        "leaveGroup": "Leave Group",
        "organization": "Company",
        "project": "Project",
        "timeoffMultiple": "CL Multiple",
        "limitDay": "CL Limitation",
        "FormulaMode": "Calculation Method",
        "payrollMultiple": "Compensation Salary Multiple",
        "note": "Remark",
        "minute": "Minute",
        "employee": "Staff",
        "overtimeRulesTitle": "OT Rules",
        "overtimeHolidayTitle": "CL Regulation",
        "overtimeSalaryTitle": "CS Regulation",
        "overtimeOtherTitle": "Other settings",
        "onlyBasicSalary": "Monthly Remuneration Calculation Base",
        "calcAsFullOT": "Does it calculate according to the duty roster?",
        "extraSubsidy": "Is Additional Compensation?",
        "extraSubsidyCompensation": "Additional Compensation",
        "extraSubsidyFormula": "Additional Calculation",
        "extraSubsidyMultiple": "Additional Compensation Multiple",
        "officeType": "Is it non-working day",
        "attdPeriod": "Duty Roster",
        "originAttdPeriod": "原有更期",
        "manHour": "Hour",
        "illegalApplyPeriod": "OT Hours cannot be within Office Hours",
        "leastOne": "At least one",
        "add": "ADD",
        "edit": "Edit",
        "delete": "Delete",
        "action": "Operation",
        "hold": "Temporary Storage",
        "hasSameValue": "Already stored in the same record",
        "needEditHour": "需要修改時數",
        "onlyBasicSalaryEnums": {
            "true": "Basic Salary",
            "false": "Basic Income"
        },
        "extraSubsidyBasic": "額外日薪酬計算基數"
    },
    "OvertimeFormDetailPage": {
        "title": "OT Application Details",
        "basicData": "Basic Information",
        "overtimeFormDetail": "OT Application Details",
        "followUp": "Review",
        "billCode": "Number:",
        "reason": "OT Reason:",
        "employee": "Staff:",
        "overtimeType": "OT Type:",
        "totalHours": "Total Duration:",
        "status": "Status:",
        "approveNote": "Approval Remarks:",
        "approvalTime": "Approval Time:",
        "createdBy": "Initiator:",
        "submitter": "Submitter:",
        "approvalBy": "Approver:",
        "submitTime": "Submission Date:",
        "createdTime": "Set up Date:",
        "workOrderNumber": "Work Order No/Name",
        "accessRecordDate": "Attendance Date",
        "fromTime": "Start Time",
        "toTime": "End Time",
        "hours": "OT Hours",
        "rules": "OT Rules",
        "compensation": "Compensation Amount",
        "remark": "Remark",
        "businessType": "Business Type:",
        "OVERTIME_PERSON": "Individual",
        "OVERTIME_BATCH": "Batch",
        "edit": "Edit",
        "department": "Department:",
        "originAttdPeriod": "原有更期",
        "attdPeriod": "Duty Roster",
        "lastestAttdPeriod": "最新更期"
    },
    "HolidayFormListPage": {
        "title": "Leave Application",
        "submitApplication": "Submit",
        "approveApplication": "Review",
        "editing": "Editing",
        "submitted": "Submitted",
        "completed": "Approved",
        "carbonCopy": "Copy",
        "processing": "Handling",
        "processed": "Proceeded",
        "billCode": "Number:",
        "department": "Department:",
        "holidayType": "Leave Group:",
        "totalDays": "Total No of Days:",
        "reason": "On Leave Reason:",
        "status": "Status:",
        "revoke": "Retrieve",
        "edit": "Edit",
        "delete": "Delete",
        "reEdit": "Re-edit",
        "rescind": "Leave Cancellation",
        "confirmRevoke": "Confirm to retrieve?",
        "confirmDelete": "Confirm to delete?",
        "revokeSuccess": "Succeed to retrieve",
        "deleteSuccess": "Succeed to delete",
        "followUp": "Review",
        "resolve": "Approved",
        "reject": "Disapproved",
        "confirmResolve": "Confirm to approve?",
        "confirmReject": "Confirm to disapprove?",
        "temporarily": "Temporarly not to proceed",
        "approveNote": "Remark",
        "applyType": "Application Type:",
        "REGULAR": "新建申請單",
        "APPEND": "補交申請單",
        "APPEND2": "補交"
    },
    "HolidayFormDetailPage": {
        "title": "Leave Application Details",
        "basicData": "Basic Information",
        "holidayFormDetail": "Leave Application Details",
        "followUp": "Review",
        "rescind": "Leave Cancellation",
        "billCode": "Number:",
        "reason": "On Leave Reason:",
        "holidayType": "Leave Group:",
        "totalDays": "Total No of Days:",
        "status": "Status:",
        "approveNote": "Approval Remarks:",
        "approvalTime": "Approval Time:",
        "createdBy": "Initiator:",
        "submitter": "Submitter:",
        "approvalBy": "Approver:",
        "submitTime": "Submission Date:",
        "createdTime": "Set up Date:",
        "startDate": "Start Date",
        "startPeriod": "Start Date",
        "endDate": "End Date",
        "endPeriod": "Start Date",
        "days": "No of Day",
        "remark": "Remark",
        "attdPeriod": "Duty Roster"
    },
    "HolidayFormPage": {
        "title": "Leave Application",
        "holidayFormDetail": "Leave Application Details",
        "holidayType": "Leave Group",
        "totalDays": "Total No of Days",
        "reason": "On Leave Reason",
        "startDate": "Start Date",
        "startPeriod": "Start Date",
        "endDate": "End Date",
        "endPeriod": "End time",
        "days": "No of Day",
        "remark": "Remark",
        "department": "Department",
        "employee": "Staff",
        "remainDate": "Annual Leave Balance",
        "leastOne": "At least one",
        "add": "ADD",
        "edit": "Edit",
        "delete": "Delete",
        "action": "Operation",
        "hold": "Temporary Storage",
        "hasSameValue": "Already stored in the same record",
        "period": "Range of periods",
        "applyTime": "Application Periods",
        "invalidStartPeriod": "Start time cannot be later than end time",
        "invalidEndDate": "End time cannot be earlies than start time",
        "notApplicable": "Not Applicable",
        "remainingDaysTip": "Insufficient remaining day of leave",
        "holidayFormRange": "選擇休假申請單明細時間範圍",
        "holidayFormDetailsTips": "點擊確認生成時，會清除列表現有的明細記錄",
        "accessRecordDate": "Attendance Date",
        "accessRecordDatePeriod": "考勤時段",
        "rangeTypeSinge": "單一時段",
        "rangeTypeMultiple": "多時段",
        "rangeType": "時段類型",
        "rangeTime": "Periods",
        "officeType": "Is it non-working day",
        "attdPeriod": "Duty Roster",
        "hoursOfLeave": "補假實際可用時數",
        "converDays": "預計轉換天數（以8小時為單位的轉換數）",
        "singleLimit": "Single Limited Days"
    },
    "CancelLeaveFormListPage": {
        "title": "Leave Withdrawal Application",
        "submitApplication": "Submit",
        "approveApplication": "Review",
        "editing": "Editing",
        "submitted": "Submitted",
        "completed": "Approved",
        "carbonCopy": "Copy",
        "processing": "Handling",
        "processed": "Proceeded",
        "billCode": "Number:",
        "department": "Department:",
        "holidayType": "Leave Group:",
        "totalDays": "Total No of Days:",
        "reason": "Leave Cancellation Reason:",
        "status": "Status:",
        "revoke": "Retrieve",
        "edit": "Edit",
        "delete": "Delete",
        "reEdit": "Re-edit",
        "confirmRevoke": "Confirm to retrieve?",
        "confirmDelete": "Confirm to delete?",
        "revokeSuccess": "Succeed to retrieve",
        "deleteSuccess": "Succeed to delete",
        "followUp": "Review",
        "resolve": "Approved",
        "reject": "Disapproved",
        "confirmResolve": "Confirm to approve?",
        "confirmReject": "Confirm to disapprove?",
        "temporarily": "Temporarly not to proceed",
        "approveNote": "Remark"
    },
    "CancelLeaveFormPage": {
        "title": "Leave withdrawal application",
        "holidayApply": "Leave Application",
        "holidayFormDetail": "Leave Application Details",
        "cancelLeaveDetail": "Leave withdrawal application details",
        "holidayType": "Leave Group",
        "totalDays": "Total No of Days",
        "reason": "Leave Cancellation Reason",
        "startDate": "Start Date",
        "startPeriod": "Start Date",
        "endDate": "End Date",
        "endPeriod": "End time",
        "days": "No of Day",
        "remark": "Remark",
        "leastOne": "At least one",
        "add": "ADD",
        "edit": "Edit",
        "delete": "Delete",
        "action": "Operation",
        "hold": "Temporary Storage",
        "hasSameValue": "Already stored in the same record",
        "outRange": "Out of the range",
        "invalidStartPeriod": "Start time cannot be later than end time",
        "invalidEndDate": "End time cannot be earlies than start time",
        "accessRecordDate": "Attendance Date",
        "rangeTime": "Periods",
        "alreadyCancelStatus": "Status",
        "alreadyCancelStatusnull": "還沒審批通過",
        "alreadyCancelStatusfalse": "通過並已更新到考勤",
        "alreadyCancelStatustrue": "已經通過銷假單據銷假",
        "addLeaveDetails": "新增銷假申請明細",
        "attdPeriod": "Duty Roster"
    },
    "CancelLeaveFormDetailPage": {
        "title": "Leave withdrawal application break down",
        "basicData": "Basic Information",
        "cancelLeaveDetail": "Leave withdrawal application details",
        "followUp": "Review",
        "billCode": "Number:",
        "reason": "Leave Cancellation Reason:",
        "holidayType": "Leave Group:",
        "totalDays": "Total No of Days:",
        "status": "Status:",
        "approveNote": "Approval Remarks:",
        "approvalTime": "Approval Time:",
        "createdBy": "Initiator:",
        "submitter": "Submitter:",
        "approvalBy": "Approver:",
        "submitTime": "Submission Date:",
        "createdTime": "Set up Date:",
        "startDate": "Start Date",
        "startPeriod": "Start Date",
        "endDate": "End Date",
        "endPeriod": "Start Date",
        "days": "No of Day",
        "remark": "Remark"
    },
    "AttendancePeriod": {
        "AM": "First half",
        "PM": "Second half"
    },
    "AttendanceApplyStatus": {
        "PENDING": "Editing",
        "APPROVING": "Pending Approval",
        "FINISHED": "Approved",
        "REJECTED": "Rejected",
        "REVOKED": "Cancelled"
    },
    "AttendanceStatus": {
        "PENDING": "Editing",
        "APPROVING": "Pending Approval",
        "FINISHED": "Approved",
        "REJECTED": "Rejected",
        "REVOKED": "Cancelled"
    },
    "CertificateApplyStatus": {
        "PENDING": "Editing",
        "APPROVING": "Processing",
        "FINISHED": "Approved",
        "REJECTED": "Rejected",
        "REVOKED": "Cancelled"
    },
    "changeApplicationPage": {
        "staffDeparture": "Departure Application",
        "performance": "Performance Appraisal Application",
        "retirement": "Retirement Application",
        "certificate": "Work Certificate Application",
        "training": "Training Sponsorship Application"
    },
    "booleanType": {
        "true": "Yes",
        "false": "No"
    },
    "departureFormListPage": {
        "title": "Departure Application",
        "submitApplication": "Submit",
        "approveApplication": "Review",
        "editing": "Editing",
        "submitted": "Submitted",
        "completed": "Approved",
        "carbonCopy": "Copy",
        "processing": "Handling",
        "processed": "Proceeded",
        "billCode": "Number:",
        "position": "Position:",
        "departureReason": "Departure Reason:",
        "lastEmploymentDate": "Departure Date:",
        "billDate": "Application Date:",
        "reason": "Remark:",
        "status": "Status:",
        "revoke": "Retrieve",
        "rescind": "Withdraw",
        "edit": "Edit",
        "delete": "Delete",
        "reEdit": "Re-edit",
        "confirmRevoke": "Confirm to retrieve?",
        "confirmRescind": "Confirm to withdraw?",
        "confirmDelete": "Confirm to delete?",
        "revokeSuccess": "Succeed to retrieve",
        "deleteSuccess": "Succeed to delete",
        "followUp": "Review",
        "resolve": "Approved",
        "reject": "Disapproved",
        "confirmResolve": "Confirm to approve?",
        "confirmReject": "Confirm to disapprove?",
        "temporarily": "Temporarly not to proceed",
        "approveNote": "Remark"
    },
    "departureFormDetailPage": {
        "title": "Departure Application Details",
        "basicData": "Basic Information",
        "followUp": "Review",
        "billCode": "Number:",
        "department": "Department:",
        "position": "Position:",
        "departureReason": "Departure Reason:",
        "lastEmploymentDate": "Departure Date:",
        "billDate": "Application Date:",
        "status": "Status:",
        "approveNote": "Approval Remarks:",
        "approvalTime": "Approval Time:",
        "createdBy": "Initiator:",
        "submitter": "Submitter:",
        "approvalBy": "Approver:",
        "createdTime": "Set up Date:",
        "submitTime": "Submission Date:",
        "reason": "Remark:"
    },
    "departureFormPage": {
        "title": "Departure Application",
        "position": "Position:",
        "departureReason": "Departure Reason:",
        "lastEmploymentDate": "Departure Date:",
        "reason": "Remark:",
        "hold": "Temporary Storage"
    },
    "performanceFormListPage": {
        "title": "Performance Appraisal Application",
        "submitApplication": "Submit",
        "approveApplication": "Review",
        "editing": "Editing",
        "submitted": "Submitted",
        "completed": "Approved",
        "carbonCopy": "Copy",
        "processing": "Handling",
        "processed": "Proceeded",
        "confirm": "Pending for confirmation",
        "billCode": "Number:",
        "position": "Position:",
        "billDate": "Application Date:",
        "performanceEvaluationDate": "90 days of Performance Evaluation:",
        "reason": "Reason:",
        "status": "Status:",
        "revoke": "Retrieve",
        "rescind": "Withdraw",
        "edit": "Edit",
        "delete": "Delete",
        "reEdit": "Re-edit",
        "confirmRevoke": "Confirm to retrieve?",
        "confirmRescind": "Confirm to withdraw?",
        "confirmDelete": "Confirm to delete?",
        "revokeSuccess": "Succeed to retrieve",
        "deleteSuccess": "Succeed to delete",
        "followUp": "Review",
        "resolve": "Approved",
        "reject": "Disapproved",
        "confirmResolve": "Confirm to approve?",
        "confirmReject": "Confirm to disapprove?",
        "temporarily": "Temporarly not to proceed",
        "approveNote": "Remark"
    },
    "performanceFormDetailPage": {
        "title": "Performance Evaluation Application details",
        "basicData": "Basic Information",
        "competenceData": "Performance Evaluation (Competence & Personality)",
        "supervisionData": "Performance Evaluation (Supervision)",
        "followUp": "Review",
        "billCode": "Number:",
        "department": "Department:",
        "position": "Position:",
        "billDate": "Application Date:",
        "joinDate": "Commencement Date:",
        "period": "Periods of Performance Evaluation:",
        "goal": "Target:",
        "achievement": "Result:",
        "jobknowledgeQqualityWwork": "Job knowledge & quality of work:",
        "productivityStability": "Productivity & stability:",
        "communicationSkills": "Communication skill:",
        "relationsCustomers": "Relations w colleagues & clients:",
        "ComplianceSystem": "Compliance to Integrated Management System (IMS):",
        "attendance": "Attendance Record:",
        "initiative": "Initiative:",
        "maturity": "Mature:",
        "integrity": "Loyalty:",
        "understandCompany": "Understand on Co and P&P:",
        "organizing": "Organizing Ability",
        "controlling": "Controlling Ability",
        "subordinates": "Managing Subordinates Skill",
        "decisionMaking": "Decision making",
        "reason": "Reason:",
        "status": "Status:",
        "approveNote": "Approval Remarks:",
        "approvalTime": "Approval Time:",
        "createdBy": "Initiator:",
        "approvalBy": "Approver:",
        "createdTime": "Set up Date:"
    },
    "ratingDefinitionsEnum": {
        "1": "Unsatisfactory",
        "2": "Marginal",
        "3": "Satisfactory",
        "4": "Commendable",
        "5": "Excellent"
    },
    "performanceFormPage": {
        "title": "Performance Evaluation Application",
        "department": "Department:",
        "position": "Position:",
        "billDate": "Application Date:",
        "reason": "Reason:",
        "hold": "Temporary Storage"
    },
    "gratiaPayment": {
        "0": "No Discretionary Bonus",
        "1": "1-month Discretionary Bonus",
        "2": "2-months Discretionary Bonus",
        "3": "3-months Discretionary Bonus"
    },
    "retirementFormListPage": {
        "title": "Retirement Application",
        "submitApplication": "Submit",
        "approveApplication": "Review",
        "editing": "Editing",
        "submitted": "Submitted",
        "completed": "Approved",
        "carbonCopy": "Copy",
        "processing": "Handling",
        "processed": "Proceeded",
        "confirm": "Pending for confirmation",
        "billCode": "Number:",
        "position": "Position:",
        "billDate": "Application Date:",
        "age65Date": "Date of turning 65:",
        "reason": "Reason:",
        "status": "Status:",
        "revoke": "Retrieve",
        "rescind": "Withdraw",
        "edit": "Edit",
        "delete": "Delete",
        "reEdit": "Re-edit",
        "confirmRevoke": "Confirm to retrieve?",
        "confirmRescind": "Confirm to withdraw?",
        "confirmDelete": "Confirm to delete?",
        "revokeSuccess": "Succeed to retrieve",
        "deleteSuccess": "Succeed to delete",
        "followUp": "Review",
        "resolve": "Approved",
        "reject": "Disapproved",
        "confirmResolve": "Confirm to approve?",
        "confirmReject": "Confirm to disapprove?",
        "temporarily": "Temporarly not to proceed",
        "approveNote": "Remark"
    },
    "retirementFormDetailPage": {
        "title": "Retirement Application Details",
        "basicData": "Basic Information",
        "followUp": "Review",
        "refereeLogNo": "File No:",
        "billCode": "Number:",
        "department": "Department:",
        "position": "Position:",
        "billDate": "Application Date:",
        "joinDate": "Commencement Date:",
        "birthDate": "Date of Birth:",
        "age65Date": "Date of turning 65:",
        "serviceYear": "Seniority:",
        "selfAverageScore": "Self-average Score:",
        "deptAverageScore": "Departmental Average Score:",
        "gratiaPayment": "Ex-gratia payment:",
        "retirement": "Retirement Approval:",
        "retirementDate": "Retirement Effective Date:",
        "extensionRetirement": "Recommend to delay retirement:",
        "extensionRetirementDate": "Recommend to delay retirement periods:",
        "reason": "Reason:",
        "status": "Status:",
        "approveNote": "Approval Remarks:",
        "approvalTime": "Approval Time:",
        "createdBy": "Initiator:",
        "submitter": "Submitter:",
        "approvalBy": "Approver:",
        "createdTime": "Set up Date:",
        "submitTime": "Submission Date:"
    },
    "retirementFormPage": {
        "title": "Retirement Application",
        "department": "Department:",
        "position": "Position:",
        "billDate": "Application Date:",
        "birthDate": "Date of Birth:",
        "age65Date": "Date of turning 65:",
        "serviceYear": "Seniority:",
        "selfAverageScore": "Self-average Score:",
        "deptAverageScore": "Departmental Average Score:",
        "gratiaPayment": "Ex-gratia payment:",
        "retirement": "Retirement Approval:",
        "retirementDate": "Retirement Effective Date:",
        "extensionRetirement": "Recommend to delay retirement:",
        "extensionRetirementDate": "Recommend to delay retirement periods:",
        "reason": "Reason:",
        "hold": "Temporary Storage"
    },
    "certificateFormListPage": {
        "title": "Work Certificate Application",
        "submitted": "Processing",
        "completed": "Approved",
        "editing": "Editing",
        "logNo": "Ref. No.:",
        "employmentVerificationType": "Type of Correspondence:",
        "reasonOfApplication": "Application Reason:",
        "reason": "Remark:",
        "delete": "Delete",
        "confirmDelete": "Confirm to delete?",
        "deleteSuccess": "Succeed to delete"
    },
    "certificateFormDetailPage": {
        "title": "Work Certificate Application Details",
        "basicData": "Basic Information",
        "logNo": "Ref. No.:",
        "employmentVerificationType": "Type of Correspondence:",
        "reasonOfApplication": "Application Reason:",
        "department": "Department:",
        "createdBy": "Initiator:",
        "createdTime": "Set up Date:",
        "reason": "Remark:",
        "createFile": "生成文件"
    },
    "certificateFormPage": {
        "title": "Work Certificate Application",
        "logNo": "Ref. No.:",
        "employmentVerificationType": "Type of Correspondence:",
        "reasonOfApplication": "Application Reason:",
        "reason": "Remark:",
        "hold": "Temporary Storage"
    },
    "employmentVerificationType": {
        "EMPLOYMENT_VERIFICATION_WITH_INCOME": "Work Certificate w Income",
        "EMPLOYMENT_VERIFICATION_WITHOUT_INCOME": "Work Certificate",
        "OTHER": "Others"
    },
    "trainingFormListPage": {
        "title": "Training Sponsorship Application",
        "editing": "Editing",
        "submitted": "Submitted",
        "completed": "Approved",
        "courseName": "Course Name:",
        "organizer": "Training Organizer / Instructor:",
        "courseType": "Course Type:",
        "startDate": "Start Date:",
        "endDate": "End Date:",
        "justificationOfAttending": "Training Reason:",
        "status": "Application Status:",
        "edit": "Edit",
        "delete": "Delete",
        "confirmDelete": "Confirm to delete?",
        "deleteSuccess": "Succeed to delete"
    },
    "trainingFormDetailPage": {
        "title": "Training Application Details",
        "basicData": "Basic Information",
        "courseName": "Course Name:",
        "organizer": "Training Organizer / Instructor:",
        "courseType": "Course Type:",
        "startDate": "Start Date:",
        "endDate": "End Date:",
        "justificationOfAttending": "Training Reason",
        "courseFeeCurrency": "Currency:",
        "courseFeeMop": "Training Course Fee (MOP):",
        "courseFee": "Training Course Fee (Foreign Currency):",
        "trainingInMacao": "Training Course Location:",
        "trainingLocation": "Other Training Course Location:",
        "transportationAmountMop": "Transportation Allowance (MOP)",
        "transportation": "Transportation Type:",
        "sharedRoom": "Accommodation Type:",
        "stayingNightsOfAccommodation": "Night(s) of Accommodation:",
        "accommodationAmountMop": "Accommodation Allowance (MOP)",
        "dailyAllowanceAmount": "Amount of Per-diem",
        "withinInTrainingBudget": "Within Training Budget",
        "createdBy": "Initiator:",
        "submitter": "Submitter:",
        "createdTime": "Application Date:",
        "submitTime": "Submission Date:"
    },
    "trainingFormPage": {
        "title": "Training Sponsorship Application",
        "courseInfo": "Training Course in details",
        "courseFeeInfo": "Training Course Fee",
        "organizer": "Training Organizer / Instructor:",
        "courseName": "Course Name:",
        "startDate": "Start Date:",
        "endDate": "End Date:",
        "justificationOfAttending": "Training Reason",
        "courseFeeCurrency": "Currency:",
        "courseFeeMop": "Training Course Fee (MOP):",
        "courseFee": "Training Course Fee (Foreign Currency):",
        "trainingInMacao": "Training Course Location:",
        "trainingLocation": "Other Training Course Location:",
        "transportationAmountMop": "Transportation Allowance (MOP)",
        "transportation": "Transportation Type:",
        "sharedRoom": "Accommodation Type:",
        "stayingNightsOfAccommodation": "Night(s) of Accommodation:",
        "accommodationAmountMop": "Accommodation Allowance (MOP)",
        "courseType": "Course Type:",
        "withinInTrainingBudget": "Within Training Budget",
        "hold": "Temporary Storage",
        sponsorship: "是否公司資助",
    },
    "justificationOfAttendingEnums": {
        "0": "Requisition by Co",
        "1": "Requisition by Staff"
    },
    "withinInTrainingBudgetEnums": {
        "0": "Yes",
        "1": "No",
        "2": "Not Applicable"
    },
    "sharedRoomEnums": {
        "true": "Twin Bed Room",
        "false": "Single Room"
    },
    "trainingLocationEnums": {
        "true": "Macau",
        "false": "Others"
    },
    "MENUS": {
        "workOrderList": "Work Orders",
        "workOrderAdd": "New Work Order",
        "assetInfo": "Assets",
        "delivery": "Deliveries",
        "noticeList": "Announcements",
        "employee": "Personal Info.",
        "suggestionList": "Suggestion Box",
        "punch": "Punch Card",
        "craftcostList": "Time Allocation",
        "worklog": "Apply Shift Change",
        "management": "Attendance",
        "materialList": "Materials",
        "approval": "Appr. Shift Change",
        "attendanceApply": "Duty Roster Application",
        "changeApplication": "人事申請",
        "materialReturnList": "物料退還申請單",
        "stockOutList": "出庫管理"
    },
    "QList": {
        "empty": "No data",
        "end": "End",
        "error": "Request failed, click to Reload"
    },
    "DataTable": {
        "yesFlag": "Yes",
        "noFlag": "No"
    },
    "PRIORITIES": {
        "1": "Critical",
        "2": "Essential",
        "3": "Normal",
        "4": "Low",
        "5": "Lowest"
    },
    "ERROR_MESSAGES": {
        "401": "Session has expired",
        "404": "Network error",
        "409": "Data duplication",
        "413": "The file size has exceeded the limit 20 MB",
        "500": "Server exception",
        "SKILLRANK_NON_EXISTENT": "Skill level must be filled",
        "ASSETACCESSORY_NON_EXISTENT": "Component must be filled",
        "ASSET_NON_EXISTENT": "Equipment must be filled",
        "ASSETAVATAR_NON_EXISTENT": "Equipment image must be uploaded",
        "ASSETSPARES_NON_EXISTENT": "Spare parts must be filled",
        "JOBPLANCRAFTCOST_NON_EXISTENT": "Manpower must be filled",
        "JOBPLANHAZARD_NON_EXISTENT": "Hazards / Precautions must be filled",
        "JOBPLANMATERIALCOST_NON_EXISTENT": "Material must be filled",
        "CODE_NON_EXISTENT": "Code must be filled",
        "JOBPLAN_NON_EXISTENT": "Job plan must be filled",
        "JOBPLANTASK_NON_EXISTENT": "Task must be filled",
        "JOBPLANTOOLCOST_NON_EXISTENT": "Tool must be filled",
        "LOCATION_NON_EXISTENT": "Location must be filled",
        "PLANMAINTAIN_NON_EXISTENT": "Planned maintenance must be filled",
        "CRAFT_NON_EXISTENT": "Craft must be filled",
        "MEASUREPOINT_NON_EXISTENT": "Measurement point must be filled",
        "MEASUREUNIT_NON_EXISTENT": "Measurement unit must be filled",
        "SUPPLIER_NON_EXISTENT": "Client must be filled",
        "EMPLOYEEATTACHMENT_NON_EXISTENT": "Staff attachments must be uploaded",
        "EMPLOYEEAVATAR_NON_EXISTENT": "Staff avatar must be uploaded",
        "EMPLOYEE_NON_EXISTENT": "Staff information must be filled",
        "POSITIONRANK_NON_EXISTENT": "Rank must be filled",
        "POSITION_NON_EXISTENT": "Position must be filled",
        "SKILL_NON_EXISTENT": "Skill information must be filled",
        "MATERIAL_NON_EXISTENT": "Material must be filled",
        "MATERIALAVATAR_NON_EXISTENT": "Material picture must be uploaded",
        "NOTICE_NON_EXISTENT": "Announcement must be filled",
        "ATTDORG_NON_EXISTENT": "Attendance group must be filled",
        "DEPARTMENT_NON_EXISTENT": "Department must be filled",
        "MAILLOG_NON_EXISTENT": "Email address to receive reminders must be filled",
        "PROJECT_MISMATCH": "Project is not consistent",
        "EITHER_DEVICE_OR_LOCATION_MUST_BE_SELECTED": "Either equipment or location must be selected",
        "ID_MUST_NOT_BE_NULL": "ID must be filled",
        "UNDESIRED_STATUS": "Unexpected Status",
        "ASSET_AND_PARENT_MISMATCH": "Equipment and Parent equipment are not consistent",
        "LOCATION_AND_PARENT_MISMATCH": "Location and parent location is not consistent",
        "ID_MUST_BE_NULL": "ID must be empty",
        "UPLOAD_EXCEPTION": "Upload Error",
        "DOWNLOAD_EXCEPTION": "Download Error",
        "AVATAR_LENGTH_OUT_OF_RANGE": "Excessive number of photos (max. ##)",
        "PLAN_MAINTAIN_JOB_PLAN_BE_USED": "PM Plan has been used",
        "UNSUPPORTED_TYPE": "Type is not supported",
        "WORK_ORDER_TYPE_MISMATCH": "Work type is not consistent",
        "WORK_ORDER_STATUS_MISMATCH": "Work order status is not consistent",
        "WORK_ORDER_STATUS_NOT_CHOICE": "Work order status has not been choosen",
        "CREATE_ENTITY_EXCEPTION": "Java save error due to data type not match",
        "CRITERIA_PARSE_ERROR": "Java parsing error due to data read/write error",
        "WORK_ORDER_IN_USED": "Work order has been used",
        "INTEGRITY_CONSTRAINT": "Integrity error",
        "JOP_PLAN_DUPLICATE": "Job Plan repeated",
        "NEXT_JOB_PLAN_NOT_FOUND": "The next Job Plan",
        "FAULT_REMEDY_DUPLICATE": "Remedy already exists",
        "FAULT_TYPE_DUPLICATE": "Failure Class already exists",
        "SCHEDULE_ADJUST_APPLY_DUPLICATE": "Revised Shift already exists",
        "STATUS_INCORRECT": "Unexpected Status",
        "SCHEDULE_ADJUST_APPLY_LENGTH_OUT_OF_RANGE": "Excessive number of revised Shifts",
        "DATA_CONVERTER_EXCEPTION": "Abnormal data conversion",
        "SYSTEM_MISMATCH": "System is not consistent",
        "GROUPORG_SHEET_NOT_FOUND": "Group Data not found",
        "ORGANIZATION_SHEET_NOT_FOUND": "Company Data not found",
        "POSITION_RANK_SHEET_NOT_FOUND": "Rank Data not found",
        "POSITION_SHEET_NOT_FOUND": "Position Data not found",
        "SKILL_SHEET_NOT_FOUND": "Skill Data not found",
        "SKILL_RANK_SHEET_NOT_FOUND": "Skill Level Data not found",
        "SYSTEM_ARCHIVES_SHEET_NOT_FOUND": "System Data not found",
        "SUPPLIER_TYPE_SHEET_NOT_FOUND": "Client Type Data not found",
        "DEPARTMENT_SHEET_NOT_FOUND": "Department Data not found",
        "EMPLOYEE_SHEET_NOT_FOUND": "Staff Data not found",
        "SUPPLIER_ARCHIVES_SHEET_NOT_FOUND": "Client Data not found",
        "LOCATION_SHEET_NOT_FOUND": "Equipment Data not found",
        "MATERIAL_TYPE_SHEET_NOT_FOUND": "Material Type Data not found",
        "MATERIAL_SHEET_NOT_FOUND": "Material Data not found",
        "PROJECT_SHEET_NOT_FOUND": "Project Data not found",
        "FAULT_TYPE_SHEET_NOT_FOUND": "Failure Class Data not found",
        "FAULT_ISSUE_SHEET_NOT_FOUND": "Problem Data not found",
        "FAULT_CAUSE_SHEET_NOT_FOUND": "Cause Data not found",
        "FAULT_REMEDY_SHEET_NOT_FOUND": "Remedy Data not found",
        "MEASURE_TYPE_SHEET_NOT_FOUND": "Measurement Type Data not found",
        "HAZARD_TYPE_SHEET_NOT_FOUND": "Hazard Data not found",
        "HAZARD_REMEDY_SHEET_NOT_FOUND": "Precaution Data not found",
        "CRAFT_SHEET_NOT_FOUND": "Craft Data not found",
        "WAREHOUSE_SHEET_NOT_FOUND": "Warehouse Data not found",
        "FILE_STUFFIX_PERMIT": "Unknown file extension",
        "QUOTE_REPEAT": "Duplicate references",
        "DATA_DUPLICATION": "Data duplication",
        "OFFICEHOUR_SHORTNAME_DUPLICATE": "Duplicate Office Hours",
        "OFFICEHOUR_IN_USE": "Office hours in use",
        "HOLIDAY_TYPE_SHEET_NOT_FOUND": "Leave Type Data not found",
        "PUBLIC_HOLIDAY_TYPE_SHEET_NOT_FOUND": "Holiday Group Data not found",
        "OFFICE_HOUR_SHEET_NOT_FOUND": "Office Hours Data not found",
        "ASSET_IN_USE": "Equipment in use",
        "PARAMETER_NOT_VALID": "Verification failed",
        "PERMISSION_DENIED": "No access right",
        "WORK_ORDER_IN_CYCLE": "Work orders stuck in a loop",
        "LOCATION_IN_CYCLE": "Locations stuck in a loop",
        "BANK_INFO_CAN_ONLY_ONE": "Employee can only hold a valid bank account",
        "OVERTIME_GREATER_THAN_INTERVAL": "OT hour overlap with normal working hour",
        "TIME_REPEAT": "Time data is duplicate",
        "GROUPPOSITION_REPEAT": "Group position is duplicate",
        "LEAVETYPERULE_NON_EXISTENT": "Data has been deleted/data does not exist",
        "OVERTIME_PERSON_CAN_ONLY_APPLY_TO_A_SINGLE_EMPLOYEE": "Individual overtime application can only be applied for an employee",
        "DATA_EMPLOYEE_DUPLICATION": "This employee has already the record, please don't input repeatedly!",
        "UPDATE_CONSTRAINT": "Unable to modify other staff information!",
        "NO_AVAILABLE_INSURANCE_PLAN_PREMIUM": "No suitable scheme of insurance premium",
        "BLUECARD_APPLY_EMPLOYEE_EXIST": "The employee has been bound",
        "ONHAND_NOT_FOUND": "No Inventory record for the Material",
        "CANCEL_DAYS_GREATER_LEAVE_DAYS": "The current no of application days exceeds the range",
        "REVOKED_COUNT_ERROR": "In/Out Record has been created, it cannot be recalled.",
        "BUSINESS_TYPE_ERROR": "Process Type workflow does not match",
        "LOCATION_IN_COUNT": "Audit in Progress, No Operation!",
        "NOT_AN_EMPLOYEE_EXCEPTION": "The applicant is not an employee",
        "APPLY_ENTITY_CONVERT_EXCEPTION": "Message Template data conversion error",
        "PROCESS_MESSAGE_EXCEPTION": "No Message Template or too many",
        "PROCESS_MESSAGE_EMPTY_EXCEPTION": "Content or Title of the Message Template is empty",
        "MESSAGE_SEND_FAILED": "Unable to obtain the assignor or approver",
        "ROLE_TYPE_ERROR_DEPARTMENT": "Role reflect error : Selected position without appointed department is error",
        "ROLE_TYPE_ERROR_PROJECT": "Role reflect error : Selected duty without appointed project is error",
        "USER_TASK_ROLE_IS_EMPTY": "User has to be assigned a role",
        "SERVICE_TASK_EXPRESSION_IS_EMPTY": "The back-end process needs to link with the expression",
        "PROCESS_EXIST_EXCEPTION": "Process definition already exists",
        "ROLE_MAPPER_EXCEPTION": "No suitable user",
        "UNSUPPORTED_RETURN_TYPE": "Unsupported type of return",
        "INVOKE_METHOD_ERROR": "Execution Failed",
        "NO_PROCESS_TYPE_FOUND": "No available configuration",
        "MULTIPLE_PROCESS_ERROR": "Multi-approval flow: Failed to configure multi-approval flow",
        "MULTIPLE_PROCESS_UPDATE_EXCEPTION": "Multi-approval flow: unable or multipul approval flow",
        "PROCESS_TYPE_LIST_IS_EMPTY": "多審批流: 配置列表爲空",
        "CONVERT_EXCEPTION": "Multiple-approval flow: Conversion error",
        "BLUE_CARD_QUOTA_ERROR": "The number of used quotas is greater than the approved quota",
        "MAP_USER_FAILED": "角色映射失敗: 用戶爲空",
        "NOT_AN_APPROVER_EXCEPTION": "The current log-in person is not an approver",
        "EMPLOYEE_ALREADY_HAS_LEAVE_TYPE_RULE_BOUND": "The employee has assigned the leave regulation",
        "TOO_MANY_PROCESS_TYPE_EXCEPTION": "Please check if there are multiple configurations with the same condition",
        "TARGET_HOLIDAY_TYPE_IS_MISSING": "The employee does not be assigned the related leave regulation",
        "ONE_EMPLOYEE_CAN_ONLY_HAVE_ONE_SPOUSE": "An employee can only have one spouse",
        "DEPENDENT_NO_FORMAT_ERROR": "The code no of Dependent is incorrect",
        "OFFICE_HOUR_CAN_NOT_BE_NULL": "Employee's duty roster cannot be blank",
        "COMPENSATION_MODE_IS_NULL": "The type of compensation cannot be blank",
        "PROCESS_SERVICE_TASK_HANDLER_NOT_FOUND": "It is unable to look for a processor to handle this type of business",
        "NOT_A_VALID_APPLY_USER": "Log-in person is not applicant, it cannot be confirmed",
        "CAN_REHIRE_NOT_SELECTED": "Please select if the employee is eligible to rehire from the edit page",
        "USER_NOT_FOUND_FROM_EMPLOYEE": "The employee has not the related user account",
        "OVERTIME_APPLY_DETAIL_IS_EMPTY": "Detail cannot be blank",
        "COMPLETE_TASK_BATCH_VALUE_ERROR": "Incorrect Parameter of multiple approval flow",
        "PROCESS_SERVICE_HANDLER_NOT_FOUND": "It is unable to look for a processor to handle this type of business",
        "EMPLOYEE_BASIC_BEAN_IS_MISSING": "The required entity does not exist in the project",
        "CUSTOM_METHOD_NOT_FOUND": "Logic for the self-defined type cannot be found",
        "CUSTOM_METHOD_TOO_MANY": "Unique self-defined logic cannot be found",
        "APPLY_REVOKE_STATUS_ERROR": "Application for withdrawal is incorrect",
        "APPLY_SUBMIT_STATUS_ERROR": "Application for submission is incorrect",
        "APPLY_APPROVING_STATUS_ERROR": "Application for pass is incorrect",
        "PROCESS_TYPE_DUPLICATE": "Configuration process is duplicated",
        "CRITERIA_ERROR_DEPT_IS_NULL": "Department cannot be blank",
        "CRITERIA_ERROR_PROJECT_IS_NULL": "Project cannot be blank",
        "CRITERIA_ERROR": "Department condition is incorrect",
        "CRITERIA_ERROR_ORG_IS_NULL": "Organization cannot be blank",
        "STATUS_IS_NOT_PENDING": "狀態非 PENDING",
        "STATUS_IS_NOT_FINISHED": "狀態非 FINISHED",
        "UNKNOWN_STATUS": "Unknown status",
        "WEB_REQUEST_FAILED": "Network request error",
        "APPLY_ID_IS_NULL": "It is necessary to obtain at least one renewal of Approval Management",
        "GENERATE_DOCUMENT_ERROR": "Generated file is incorrect",
        "BANK_INFO_ERROR": "Employees can only have a valid bank account",
        "SPOUSE_CODE_TABLE_IS_NULL": "The relationship of spouse cannot be blank",
        "TYPE_NOT_ACCEPT": "This type of attachment",
        "PARAMETER_IS_NULL": "There is empty parameter in the document template",
        "TOO_MANY_ATTACHMENT_EXCEPTION": "The number of the attachment is not unique",
        "DATE_ERROR": "Parameter error",
        "EMPLOYEE_CAN_ONLY_HAVE_ONE_SA": "Employee can only have a services agreement",
        "EMPLOYEE_ID_NOT_NULL": "Employee's ID cannot be blank",
        "MATERIAL_SHOULD_BE_UNIQUE_IN_ONE_APPLY": "The same material can only exist once in an application",
        "ACTUAL_STOCK_NUM_IS_LESS_THAN_APPLY": "Material in stock is less than the requisition",
        "WAREHOUSE_LOCATION_IN_CYCLE": "Store location is in a loop",
        "ACTUAL_STOCK_NUM_IS_LESS_THAN_REQUIRE": "Material in stock is less than the requisition",
        "MATERIAL_CATEGORY_IN_CYCLE": "Material Type is in a loop",
        "EMPLOYEE_LIST_IS_NULL": "Employee data list is blank",
        "SCHEDULE_ADJUST_IS_EMPTY": "The last shift is blank",
        "APPLY_REVOKE_FAILED_STATUS_ERROR": "The status of withdrawal application is wrong",
        "APPLY_SUBMIT_FAILED_STATUS_ERROR": "Application for submission is incorrect",
        "EMPLOYEE_IS_DEPARTURE": "The employee has resigned from the Company and cannot submit the application",
        "NOT_IN_A_VALID_LIMIT_TYPE": "The employee has not the regulation of the related entitlement",
        "APPLY_APPROVING_FAILED_STATUS_ERROR": "The status of agreed application is wrong",
        "EMPLOYEE_NOT_FOUND": "The employee does not exist",
        "HOLIDAY_TYPE_NOT_FOUND": "The type of leave does not exist",
        "LEAVE_APPLY_DETAIL_NOT_FOUND": "Leave application details cannot be found",
        "SCHEDULE_ADJUST_MISSING": "Missing duty roster record",
        "SCHEDULE_ADJUST_DATE_MISMATCH": "Duty Roster record does not match",
        "LEAVE_TYPE_NOT_ACCEPT": "The type of the record does not support",
        "HOLIDAY_TYPE_SELECTED_MIX": "Duplicate leave type",
        "QUOTA_SAME_ERROR": "Entitlement calculation is same",
        "QUOTA_GENERATE_ERROR": "Entitlement generation error",
        "AUTO_GENERATE_RECORD_NOT_ONLY": "Auto Entitlement Generation is not unique",
        "STATUS_ERROR": "狀態非 PENDING 或 APPROVING",
        "OFFICE_HOUR_IS_NOT_A_WORKING_DAY": "Working hour is not a valid schedule",
        "IMPORT_DATA_IS_EMPTY": "Import data is blank",
        "EMPLOYEE_ORG_IS_NOT_THE_SAME": "Staff {0} not belongs to the selected company",
        "EMPLOYEE_DO_NOT_HAVE_THIS_OFFICE_HOUR": "There is no shift plan on the attendance group for staff {0}",
        "IMPORT_OFFICE_HOUR_IS_NULL": "There is no office hour set for staff {0}",
        "IMPORT_OFFICE_HOUR_IS_NOT_A_WORKING_DAY": "It is not a valid working day for staff {0}",
        "APPLY_REVOKE_FAILED": "Withdrawal application is failed",
        "THE_CALCULATION_METHOD_IS_NOT_SELECTED": "Without select appropriate compensation type and calculation",
        "DETAILS_DUPLICATE_ERROR": "The new organization has the record into the database",
        "NUM_ERROR": "Material quantity must be greater than 0",
        "STOCK_COUNT_ID_REQUIRED": "Inventory Audit ID cannot be empty",
        "STOCK_COUNT_BODY_ID_REQUIRED": "Inventory Audit Details ID cannot be empty",
        "SOURCE_INFO_REQUIRED": "Original Source Information cannot be empty",
        "STOCK_IN_ID_REQUIRED": "Stock IN ID cannot be empty",
        "STOCK_IN_BODY_ID_REQUIRED": "Stock Details ID cannot be empty",
        "DEPARTURE_REQUIRE_PART_IS_NOT_COMPLETE": "The department head does not fill in the information required for the departure application",
        "WAREHOUSE_LOCATION_ID_IS_MISSING": "{0} Material Location Code is empty",
        "GENERATE_PARAMETER_IS_MISSING": "{0} parameter for the required document is empty",
        "EMPLOYEE_SCHEDULE_ADJUST_IS_EMPTY": "員工考勤更期為空",
        "EMPLOYEE_HAS_ALREADY_APPLIED": "員工已經有一條申請",
        "LEAVE_APPLY_DETAIL_DUPLICATE": "請假詳情單數據已存在",
        "LEAVE_CANCEL_APPLY_DETAILS_IS_EMPTY": "銷假單據子單據爲空",
        'CAN_NOT_FOUND_FIT_LEAVE_TYPE_IN_EMPLOYEE': '員工無綁定休假組別', // 二期翻譯，待提供
        "REACH_MAX_SINGLE_LIMIT_DAYS": "請假天數超出最大許可天數",
        LEAVE_APPLY_SCHEDULE_ADJUST_CAN_NOT_BE_NULL: `請假單不能請無考勤的單據`,
        "exceptionCodes": {
            "entryDate": "The commencement date of employee is blank",
            "identification": "員工身份信息爲空",
            "identificationParams": "員工身份信息身份證類型，身份證編號爲空"
        },
        "FILE_SIZE_TOO_LARGE": "The file size has exceeded the limit 20 MB"
    },
    "common": {
        "function": "Function Shortcut",
        "noData": "No data",
        "dataError": "Data exception",
        "confirm": "OK",
        "cancel": "Cancel",
        "noMore": "End",
        "loadError": "Request failed, click to Reload",
        "pleaseChoose": "Please select",
        "choose": "Select",
        "cannotChoose": "This item is not selectable",
        "delete": "Delete",
        "maxLength16": "Max. length is 16",
        "entityTooLarge": "The file size has exceeded the limit 20 MB",
        "viewNotification": "Go to view?",
        "update": "New version is available for update"
    },
    "RecorderComponent": {
        "end": "Click to end",
        "start": "Click to start"
    },
    "PickerComponent": {
        "pleaseInputCode": "Please fill the code",
        "codeMustNotNull": "Code cannot be empty",
        "assetNotFound": "Can't find the Equipment",
        "locationNotFound": "Can't find the Location"
    },
    "form": {
        "choose": "Please Select",
        "submit": "Submit",
        "reset": "Reset",
        "itemRequire": "Required field",
        "mustBeNumber": "Must be numeric",
        "notZero": "Must be positive",
        "submitSuccess": "Submitted successfully",
        "operationSuccess": "Successful operation",
        "save": "儲存",
        "add": "ADD",
        "edit": "Edit",
        "delete": "Delete",
        "action": "Operation",
        "hold": "Temporary Storage"
    },
    "STATUS": {
        "A": "Enabled",
        "C": "Disabled"
    },
    "ABSENCE_TYPE": {
        "LATE": "Late",
        "DOCTOR": "Consult doctor",
        "FOLLOW": "Accompany to consult doctor",
        "OUT": "External work",
        "FORGOT": "Forgot to punch card",
        "TRAINING": "Attend training or seminar",
        "OTHER": "Other"
    },
    "DAILY_ACCESS_RECORD_TYPE": {
        "TODAY": "To Be Determined",
        "NORMAL": "Normal",
        "LATE": "Late",
        "LEAVE_EARLY": "Early Leave",
        "ABSENT": "Absence",
        "ON_LEAVE": "Other Leave",
        "NON_WORKING_DAY": "Non-Working Day",
        "PUBLIC_HOLIDAY": "Holiday",
        "MISSING_CARD_PUNCH": "Missing Punch Record"
    },
    "LanguagePage": {
        "title": "Language"
    },
    "HomePage": {
        "home": "Home",
        "person": "Profile",
        "workOrder": "WO",
        "assetInfo": "Assets",
        "materialRequestForm": "Materials",
        "materialRequestFormArrival": "Deliveries",
        "jobDiary": "Calendar",
        "punch": "Punch Card",
        "attendance": "Attendance",
        "employeeInfo": "Staff Corner",
        "employeeMustrequired": "Account not linked to a Staff, cannot use this function",
        "suggestion": "Suggestion Box",
        "notice": "Announcements",
        "approval": "Approve  Shift Changing Application",
        "craftCost": "Manpower Cost",
        "dev": "Stay Tuned",
        "search": "Search function...",
        "taskManagementGroup": "Task Management",
        "staffCornerGroup": "Staff Corner"
    },
    "ErrorPage": {
        "title": "Error Page",
        "pageNotFount": "Broken link",
        "noPremission": "No access permission"
    },
    "LoginPage": {
        "title": "Welcome to CESL Asia iPlatform",
        "welcomeBack": "Welcome Back, ",
        "continue": "Sign in to continue",
        "username": "Username",
        "password": "Password",
        "loginError": "Invalid Username or Password",
        "forgotPassword": "Forgot Password?",
        "login": "Log In"
    },
    "ChangePasswordPage": {
        "title": "Change Password",
        "oldPassword": "Current Password",
        "newPassword": "New Password",
        "confirmPassword": "Confirm Password",
        "passwordNotMatch": "Passwords do not match"
    },
    "ForgotPasswordPage": {
        "title": "Password Recovery",
        "username": "Username",
        "mobile": "Phone No.",
        "verificationCode": "Verification Code",
        "send": "Send",
        "resend": "Resend",
        "countDown": "Resend in {0} seconds",
        "sendSuccess": "Sent successfully",
        "invalidVerificationCode": "Verification Code is invalid",
        "usernameOrMobileInvalid": "Username or mobile phone number is incorrect"
    },
    "ResetPasswordPage": {
        "title": "Reset Password",
        "newPassword": "New Password",
        "confirmPassword": "Confirm Password",
        "passwordNotMatch": "Passwords do not match"
    },
    "EmployeeInfoPage": {
        "title": "Personal Information",
        "entryDate": "Join: ",
        "skill": "Skill",
        "document": "File",
        "baseInfo": "Basic Information",
        "idNo": "ID/Passport No.",
        "issueDate": "ID Issue Date",
        "expiryDate": "ID Expiry Date",
        "maritalStatus": "Marital Status",
        "macauAddress": "Macau Address",
        "homePhone": "Macau Home Phone No.",
        "mobile": "Macau Mobile Phone No.",
        "hometownAddressOrPhone": "Place of Origin Address and Phone No(For Non Macau Resident)",
        "urgencyContact": "Urgency Contact",
        "urgencyContactName": "Name of Urgency Contact",
        "contactNo": "Contact No.",
        "educational": "Educational/ Professional Qualifications",
        "institution": "Name of Institution",
        "field": "Field",
        "major": "Major/ Course Studied",
        "qualification": "Qualification Obtained",
        "family": "Family Background (Information for Spouse and Children ONLY)",
        "familyName": "Name",
        "relationship": "Relationship",
        "gender": "Gender",
        "birthDate": "Date of Birth",
        "fileOrigin": "文件來源",
        "fileOriginEnums": {
            "EMPLOYEE": "Staff",
            "EMPLOYEE_LICENSES": "License",
            "EMPLOYEE_TRAINING": "Training",
            "EMPLOYEE_WARNING": "Warning",
            "EMPLOYEE_EDUCATIONAL": "Education Background",
            "EMPLOYEE_WORKING_HISTORY": "Working Experience",
            "EMPLOYEE_FAMILY": "Family Member",
            "EMPLOYEE_CONTRACT_HISTORY": "合同紀錄"
        },
        "description": "描述",
        "fileName": "Description",
        "licenses": "License",
        "licensesName": "License",
        "licensesType": "License Type",
        "remark": "Remark",
        "issueOrganization": "Issue Organization",
        "issueLicensesDate": "Issue Date",
        "expiryLicensesDate": "Expiry Date",
        "sponsoredByCompany": "Sponsored by Company?",
        "sponsoredAmount": "Sponsorship Amount"
    },
    "relationshipEnums": {
        "SPOUSE": "Spouse",
        "SON": "Son",
        "DAUGHTER": "Daughter"
    },
    "genderEnums": {
        "0": "M",
        "1": "F"
    },
    "maritalStatusEnums": {
        "UNMARRIED": "Single",
        "MARRIED": "Married",
        "DIVORCED": "Divorced",
        "WIDOWED": "Widowed"
    },
    "AdjustmentPage": {
        "title": "Apply Shift Changes",
        "employee": "Applicant",
        "startDate": "From",
        "endDate": "To",
        "originalOfficeHour": "Current Shift Type",
        "attdOrg": "Intended Attendance Group",
        "newOfficeHour1": "1st Half Shift",
        "newOfficeHour2": "2nd Half Shift",
        "reason": "Reason",
        "tip": "The selected period must be in the same Attendance Group and the same daily Shift",
        "repeat": "Duplicate application"
    },
    "AdjustmentDetailPage": {
        "title": "Application Details",
        "applicant": "Applicant: ",
        "startDate": "From: ",
        "endDate": "To: ",
        "originalOfficeHour": "Current Shift: ",
        "attdOrg": "Attendance Group: ",
        "newOfficeHour": "Intended Shift: ",
        "status": "Status: ",
        "reason": "Reason: ",
        "createdTime": "Submitted on: "
    },
    "AdjustmentRecordsPage": {
        "applicant": "Applicant: ",
        "startDate": "From: ",
        "endDate": "To: ",
        "status": "Status: ",
        "reason": "Reason: ",
        "recall": "Recall",
        "edit": "Edit Application",
        "recallSuccess": "Recalled successfully"
    },
    "ADJUSTMENT_RECORDS_STATUS": {
        "S": "Submitted",
        "C": "Recalled",
        "N": "Rejected",
        "P": "Approved"
    },
    "AbsencePage": {
        "title": "Justify Absence",
        "applyDate": "Absence Date",
        "fromTime": "From",
        "toTime": "To",
        "reasonType": "Absence Type",
        "reason": "Reason"
    },
    "AbsenceDetailPage": {
        "title": " Justification Details",
        "applicant": "Applicant: ",
        "applyDate": "Absence Date: ",
        "fromTime": "From: ",
        "toTime": "To: ",
        "status": "Status: ",
        "reasonType": "Absence Type: ",
        "reason": "Reason: "
    },
    "PunchPage": {
        "title": "Punch Card",
        "myPosition": "My Location",
        "positioningFailed": " Failed to set Location",
        "rePositioning": "Reset Location",
        "punchWait": "Too many card punches, please try again later",
        "punch": "Punch Card",
        "punchSuccess": "Card punched successfully",
        "weakGPSSignl": "GPS signal is weak"
    },
    "PunchRecordsPage": {
        "title": "Card Punch Record",
        "date": "Date: "
    },
    "DutyRosterPage": {
        "myDutyRoster": "My Shift",
        "groupDutyRoster": "Attendance Groups"
    },
    "JobDiaryPage": {
        "title": "Work Calendar",
        "dutyRoster": "Calendar",
        "adjustment": "Shift Applications"
    },
    "AttendancePage": {
        "title": "Attendance Management",
        "reports": "Attendances",
        "absence": "Justifications"
    },
    "AttendanceReportsPage": {
        "week": "Week",
        "month": "Month",
        "followUp": "Justify",
        "dailyAccessRecordType": "Type: ",
        "attdOrgName": "Group: ",
        "officeHours": "Shift: ",
        "durations": "Time: ",
        "lateMins": "Late (min): ",
        "leaveMins": "Early Leave (min): "
    },
    "AttendanceDetailPage": {
        "title": "Attendances",
        "followUp": "Justify",
        "dailyAccessRecordType": "Type: ",
        "attdOrgName": "Group: ",
        "officeHours": "Shift: ",
        "durations": "Time: ",
        "lateMins": "Late (min): ",
        "leaveMins": "Early Leave (min): ",
        "processed": "Done"
    },
    "AttendanceAbsencePage": {
        "applicant": "Applicant: ",
        "applyDate": "Absence Date: ",
        "status": "Status: ",
        "reasonType": "Absence Type: "
    },
    "MATERIAL_REQUEST_STATUS": {
        "A": "Editing",
        "S": "Submitted",
        "N": "Rejected",
        "P": "Approved",
        "R": "Approved"
    },
    "SUGGESTION_STATUS": {
        "C": "Recalled",
        "R": "Replied",
        "S": "Submitted"
    },
    "AssetInfoPage": {
        "title": "Assets",
        "project": "Project",
        "asset": "Equipment",
        "location": "Location"
    },
    "AssetPage": {
        "title": "Equipment Information",
        "code": "Code: ",
        "codePlaceholder": "Please input the Code here",
        "name": "Description: ",
        "specification": "Model: ",
        "sn": "Serial No.: ",
        "tagNo": "Tag No.: ",
        "maintenanceCost": "Maintenance Cost: ",
        "maintenanceMinutes": "Downtime: ",
        "system": "System: ",
        "parent": "Parent: ",
        "faultType": "Failure Class: ",
        "supplier": "Vendor: ",
        "location": "Location: ",
        "installedDate": "Install Date: ",
        "useStartTime": "Usage Period: ",
        "warrantyDate": "Warranty until: ",
        "priority": "Priority: ",
        "accessory": "Spare Parts",
        "material": "Materials",
        "num": "Qty",
        "spares": "Components",
        "warehouse": "WHSE",
        "canNotEmpty": "Code cannot be empty"
    },
    "LocationPage": {
        "title": "Location Information",
        "code": "Code: ",
        "tagNo": "Tag No.: ",
        "codePlaceholder": "Please input the Code here",
        "name": "Name: ",
        "parent": "Parent: ",
        "faultType": "Failure Class: ",
        "priority": "Priority: ",
        "canNotEmpty": "Code cannot be empty"
    },
    "CalendarPage": {
        "title": "Attendance Calendar",
        "dailyAccessRecordType": "Type: ",
        "attdOrgName": "Group: ",
        "officeHours": "Shift: ",
        "durations": "Time: ",
        "followUp": "Justify",
        "attTime": "Punch: ",
        "fromTime": "From: ",
        "toTime": "To: ",
        "break": "Rest",
        "reports": "Attendance Managment",
        "lateMins": "Late (min): ",
        "leaveMins": "Early Leave (min): ",
        "processed": "Done",
        "attdInfo": "考勤信息",
        "leaveStatistics": "休假統計",
        "leaveType": "Leave Type",
        "lastYearBalance": "Last Year C/D",
        "currentYearBalance": "Current Year Entitlement",
        "approvedThisYear": "Approved Days (this year)",
        "approvedNextYear": "Approved Days (the next calendar year)",
        "waitingForApproved": "Pending for Approval",
        "adjustDays": "Adjustment",
        "yearlyEndEstBalance": "Year End Est. Balance",
        "consumeOnMarch": "Required to consume before End of March",
        "consumeOnDecember": "Required to consume before End of December",
        "entitlementAsAtCME": "Entitlement As at Curent Month End",
        "balanceAsAtCME": "截至本月尾之餘額",
        "toDepartment": "部門休假摘要"
    },
    "DepartmentPage": {
        "title": "部門休假摘要",
        "employee": "Staff",
        "department": "Department"
    },
    "MaterialRequestFormPage": {
        "title": "Material Requisition",
        "meterialRequestFormDetail": "Details",
        "leastOne": "(At least one item)",
        "add": "New",
        "edit": "Edit",
        "delete": "Delete",
        "material": "MATL",
        "warehouse": "WHSE",
        "num": "Qty",
        "waitReceiveNum": "待領用數量",
        "receiveNum": "已領用數量",
        "onhandNum": "可用庫存量",
        "workOrder": "WO",
        "supplier": "供應商",
        "action": "OPS",
        "employee": "Staff",
        "project": "Project",
        "department": "Department",
        "category": "用戶類別",
        "expectedDate": "預計使用日期",
        "expectedReturnDate": "預計歸還日期",
        "applyNote": "單據描述",
        "hold": "Temporary Storage",
        "applyType": "Application Type",
        "hasSameValue": "Already stored in the same record",
        "reason": "Remark",
        "materialDetails": "物料明細",
        "purchaseRequisition": "採購申請",
        "materialUnit": "庫存單位",
        "materialType": "物料類型",
        "materialCategory": "物料類目",
        "mainSpecification": "庫存規格",
        "defaultApplyNote": "{0} 的物料申請單",
        "convertPurchase": "轉為採買"
    },
    "MaterialRequestFormBusinessType": {
        "MRA": "物料領用",
        "MI": "物料入庫",
        "GI": "贈品入庫",
        "CI": "客戶物料入庫",
        "NI": "一般入庫",
        "NO": "一般出庫",
        "SR": "入庫退回出庫",
        "INVENTORY_COUNT": "盤點單",
        "TO": "工具借出",
        "RM": "物料申領",
        "BD": "文件借閲",
        "CO": "客戶物料取出",
        "RO": "維護出庫",
        "DO": "報廢出庫",
        "AO": "人員/部門領用",
        "TR": "工具退還",
        "MR": "物料退還",
        "DR": "文件退還",
        "CR": "客戶物料退還",
        "RR": "維護入庫",
        "AR": "人員/部門退還"
    },
    "MaterialRequestFormStatus": {
        "PENDING": "Editing",
        "APPROVING": "Pending Approval",
        "FINISHED": "Approved",
        "REJECTED": "Rejected",
        "REVOKED": "Cancelled",
        "WAITING_FOR_OUT_OF_STOCK": "待出庫",
        "WAITING_FOR_STOCK_IN": "待入庫",
        "ALL_RECEIVE_WAITING_FOR_CONFIRM": "全部到貨，待確認",
        "PART_RECEIVE_WAITING_FOR_CONFIRM": "部份到貨，待確認",
        "ALL_RECEIVE": "全部到貨",
        "PART_RECEIVE": "部分到貨",
        "WAITING_FOR_RECEIVE": "待領用",
        "ALREADY_RECEIVED": "已領用"
    },
    "MaterialRequestFormCategory": {
        "0": "Internal",
        "1": "Client"
    },
    "MaterialRequestFormListPage": {
        "title": "Material Requisition",
        "department": "Department:",
        "project": "Project: ",
        "category": "用戶類別：",
        "submitApplication": "Submit",
        "approveApplication": "Approval",
        "carbonCopy": "Copy",
        "editing": "Editing",
        "submitted": "Submitted",
        "delivers": "待出庫",
        "completed": "Approved",
        "processing": "Pending",
        "billCode": "Code: ",
        "num": "申請數量：",
        "receiveTotal": "已領用數量：",
        "expectedDate": "預計使用日期：",
        "status": "Status: ",
        "recall": "Recall",
        "edit": "Edit",
        "confirm": "OK",
        "cancel": "Cancel",
        "confirmRecall": "Recall?",
        "recallSuccess": "Recalled successfully",
        "confirmDelete": "Delete",
        "deleteSuccess": "Succeed to delete",
        "followUp": "Approval",
        "resolve": "Approve",
        "reject": "Reject",
        "quickCollection": "快速領用",
        "confirmResolve": "Approve?",
        "confirmReject": "Reject?",
        "temporarily": "Process later",
        "approveNote": "Remarks",
        "approveNote1": "Remarks: ",
        "applyNote": "單據描述：",
        "applyType": "Application Type:",
        "reason": "Remark:",
        "delete": "Delete"
    },
    "MaterialRequestFormDetailPage": {
        "title": "Requisition Details",
        "organization": "Company:",
        "department": "Department:",
        "project": "Project:",
        "category": "用戶類別：",
        "basicData": "Basic Information",
        "followUp": "Approval",
        "billCode": "Code: ",
        "status": "Status: ",
        "expectedDate": "預計使用日期：",
        "expectedReturnDate": "預計歸還日期：",
        "applyNote": "單據描述：",
        "approveNote": "Remarks: ",
        "receiveDate": "Received Date: ",
        "meterialRequestFormDetail": "物料明細",
        "purchaseRequisition": "採購申請",
        "material": "MATL",
        "warehouse": "WHSE",
        "createdBy": "Requested by: ",
        "promoter": "Initiator:",
        "num": "Req. Qty",
        "waitReceiveNum": "AWR Qty",
        "receiveNum": "Rec. Qty",
        "workOrder": "WO",
        "billDate": "Submitted on: ",
        "createdTime": "Created on: ",
        "applyType": "Application Type:",
        "materialUnit": "庫存單位",
        "materialType": "物料類型",
        "materialCategory": "物料類目",
        "mainSpecification": "Specifications",
        "supplier": "供應商",
        "detailsReason": "Remark",
        "reason": "Remark:"
    },
    "MaterialReturnFormPage": {
        "title": "物料退還申請單",
        "meterialRequestFormDetail": "物料退還明細",
        "leastOne": "At least one",
        "add": "ADD",
        "edit": "Edit",
        "delete": "Delete",
        "material": "物料",
        "num": "申請數量",
        "receivedQuantity": "領用數量",
        "workOrder": "工單",
        "action": "Operation",
        "employee": "Staff",
        "project": "Project",
        "department": "Department",
        "returnDate": "退還日期",
        "expectedReturnDate": "預計歸還日期",
        "returnNum": "退還數量",
        "materialCurrentReturnNums": "本次退還數量",
        "returnNumHistory": "已退還數量",
        "applyNote": "單據描述",
        "hold": "Temporary Storage",
        "applyType": "退還類型",
        "hasSameValue": "Already stored in the same record",
        "invalidReturnNum": "退還數量不能超過申請數量",
        "positiveInteger": "此項為正整數",
        "reason": "Remark",
        "materialDetails": "物料退還明細",
        "materialUnit": "庫存單位",
        "materialType": "物料類型",
        "materialCategory": "物料類目",
        "mainSpecification": "庫存規格",
        "defaultApplyNote": "{0} 的物料退還申請單",
        "batchNo": "批次號",
        "sourceDocument": "來源單據：",
        "warehouse": "倉庫",
        "receiveWareHouse": "貨位"
    },
    "MaterialReturnFormListPage": {
        "title": "物料退還申請單",
        "department": "Department:",
        "project": "Project:",
        "submitApplication": "Submit",
        "approveApplication": "Review",
        "carbonCopy": "Copy",
        "editing": "Editing",
        "submitted": "Submitted",
        "delivers": "待入庫",
        "completed": "Approved",
        "processing": "Handling",
        "billCode": "Number:",
        "num": "退還數量：",
        "returnDate": "退還日期：",
        "status": "Status:",
        "recall": "Retrieve",
        "edit": "Edit",
        "confirm": "OK",
        "cancel": "Cancel",
        "confirmRecall": "Confirm to retrieve?",
        "recallSuccess": "Succeed to retrieve",
        "confirmDelete": "Delete",
        "deleteSuccess": "Succeed to delete",
        "followUp": "Review",
        "resolve": "Approved",
        "reject": "Disapproved",
        "confirmResolve": "Confirm to approve?",
        "confirmReject": "Confirm to disapprove?",
        "temporarily": "Temporarly not to proceed",
        "approveNote": "Remark",
        "approveNote1": "Remark:",
        "applyNote": "單據描述：",
        "applyType": "退還類型：",
        "quickReturn": "快速退還",
        "reason": "Remark:",
        "delete": "Delete"
    },
    "MaterialReturnFormDetailPage": {
        "title": "物料退還申請單詳情",
        "organization": "Company:",
        "department": "Department:",
        "project": "Project:",
        "basicData": "Basic Information",
        "followUp": "Review",
        "billCode": "Number:",
        "status": "Status:",
        "returnDate": "退還日期：",
        "expectedReturnDate": "預計歸還日期：",
        "applyNote": "單據描述：",
        "approveNote": "Remark:",
        "meterialReturnFormDetail": "物料退還明細",
        "material": "物料",
        "createdBy": "Submitter:",
        "promoter": "Initiator:",
        "num": "申請數量",
        "returnNum": "退還數量",
        "receivedQuantity": "領用數量",
        "materialCurrentReturnNums": "本次退還數量",
        "workOrder": "工單編號",
        "billDate": "Submission Date:",
        "createdTime": "Set up Date:",
        "applyType": "退還類型：",
        "materialUnit": "庫存單位",
        "materialType": "物料類型",
        "materialCategory": "物料類目",
        "mainSpecification": "庫存規格",
        "detailsReason": "Remark",
        "reason": "Remark:",
        "sourceDocument": "來源單據：",
        "batchNo": "批次號"
    },
    "StockOutFormListPage": {
        "title": "出庫單",
        "department": "Department:",
        "project": "Project:",
        "category": "用戶類別：",
        "waitingList": "待出庫列表",
        "receiptConfirmationList": "出庫確認列表",
        "delivers": "待出庫",
        "confirmed": "部分出庫，待確認",
        "partialDelivery": "部分出庫",
        "processing": "待出庫",
        "requisitioned": "待領用",
        "completed": "Approved",
        "billCode": "Number:",
        "num": "申請出庫數量：",
        "status": "Status:",
        "edit": "Edit",
        "confirm": "OK",
        "cancel": "Cancel",
        "approveNote": "Remark",
        "applyNote": "單據描述：",
        "applyType": "出庫類型：",
        "materialNumDetail": "物料數量詳細",
        "reason": "Remark:",
        "materialNo": "物料編號/名稱",
        "waitReceiveNum": "待出庫數量",
        "receiveNum": "已出庫數量",
        "actualArrivalNum": "實際領用數量：",
        "billDate": "出庫日期：",
        "warehouse": "倉庫："
    },
    "StockOutApprovalStatus": {
        "PENDING": "待出庫",
        "APPROVING": "待領用",
        "FINISHED": "Approved"
    },
    "StockOutFormDetailPage": {
        "title": "出庫單詳情",
        "organization": "Company:",
        "department": "Department:",
        "project": "Project:",
        "basicData": "Basic Information",
        "billCode": "Number:",
        "category": "用戶類別：",
        "deliveryDate": "出庫日期：",
        "warehouse": "倉庫：",
        "status": "Status:",
        "applyNote": "單據描述：",
        "approveNote": "Remark:",
        "stockOutDetail": "出庫明細",
        "materialNo": "物料編號/名稱",
        "material": "物料",
        "createdBy": "Submitter:",
        "promoter": "Initiator:",
        "business": "業務人員：",
        "createdTime": "Set up Date:",
        "applyType": "Business Type:",
        "materialUnit": "庫存單位",
        "materialType": "物料類型",
        "materialCategory": "物料類目",
        "mainSpecification": "庫存規格",
        "num": "申請出庫數量",
        "availableNum": "可用庫存量",
        "quantityToBeIssued": "待出庫數量",
        "receiveNum": "已出庫數量",
        "waitReceiveNum": "待領用數量",
        "reason": "Remark:",
        "batchNo": "批次號",
        "operation": "Operation",
        "cargoSpace": "貨位",
        "availableStock": "現存量",
        "currentQuantity": "本次出庫數量",
        "outboundLocation": "出庫庫位",
        "checkWarehouseInventory": "查看倉庫現存量",
        "delete": "Delete"
    },
    "StockOutFormPage": {
        "title": "出庫申請單",
        "stockOutFormDetail": "出庫明細",
        "leastOne": "At least one",
        "add": "ADD",
        "edit": "Edit",
        "delete": "Delete",
        "material": "物料",
        "materialNo": "物料編號/名稱",
        "num": "申請數量",
        "receivedQuantity": "領用數量",
        "workOrder": "工單編號",
        "action": "Operation",
        "employee": "Staff",
        "project": "Project",
        "department": "Department",
        "applyNote": "單據描述",
        "hold": "Temporary Storage",
        "applyType": "出庫類型",
        "hasSameValue": "Already stored in the same record",
        "positiveInteger": "此項為正整數",
        "reason": "Remark",
        "materialUnit": "庫存單位",
        "materialType": "物料類型",
        "materialCategory": "物料類目",
        "mainSpecification": "庫存規格",
        "availableNum": "可用庫存量",
        "receiveNum": "已領用數量",
        "quantityToBeIssued": "待出庫數量",
        "waitReceiveNum": "待領用數量",
        "currentIssueQuantity": "本次出庫數量",
        "defaultApplyNote": "{0} 的出庫申請單",
        "businessType": "Business Type",
        "batchNo": "批次號",
        "sourceDocument": "來源單據",
        "category": "用戶類別",
        "warehouse": "出庫倉庫",
        "warehouseLocation": "出庫庫位",
        "operation": "Operation",
        "availableStock": "現存量",
        "currentQuantity": "本次出庫數量",
        "outboundLocation": "出庫庫位",
        "receiveWareHouse": "貨位",
        "checkWarehouseInventory": "查看倉庫現存量",
        "invalidQuantityNum": "出庫數量不能大於最大值{0}"
    },
    "Attachment": {
        "attachment": "Attachment",
        "upload": "Upload",
        "filename": "File name",
        "action": "Operation",
        "download": "Download",
        "delete": "Delete",
        "uploadSuccess": "Uploaded successfully",
        "confirmDelete": "Delete?",
        "deleteSuccess": "Deleted successfully",
        "nonPDFFiles": "PDF files only"
    },
    "WorkOrderPage": {
        "title": "New Work Order",
        "project": "Project",
        "workOrderType": "Work Type",
        "nextStep": "Next",
        "assetType": "Equipment",
        "locationType": "Location",
        "otherType": "Others",
        "asset": "Equipment",
        "location": "Location ",
        "faultType": "Class",
        "faultIssue": "Problem",
        "referCode": "Reference",
        "submitter": "Report By",
        "priority": "Priority",
        "description": "Description",
        "submitWithError": "Work Order was submitted successfully, but the media files may be lost!",
        "dataNotFount": "Data Not Found",
        "billDate": "Reported"
    },
    "WorkOrderListPage": {
        "title": "Work Orders List",
        "allWorkOrder": "All Order",
        "ownerWorkOrder": "My Order",
        "project": "Project: ",
        "waiting": "Pending",
        "underway": "In Process",
        "completed": "Approved",
        "asset": "Equip.: ",
        "location": "Loc.: ",
        "billCode": "WO: ",
        "referCode": "Reference: ",
        "status": "Status: ",
        "description": "Desc.: ",
        "search": "Search",
        "keyword": "Keywords",
        "keywordLabel": "WO / Eqpt./ Loc./ Desc.",
        "workOrderType": "Work Type",
        "workOrderStatus": "Status",
        "createdTime": "Created on",
        "actualStartTime": "Actual Start",
        "actualEndTime": "Actual Finish"
    },
    "PlanCraftCostPage": {
        "title": "Planned Manpower",
        "craft": "Craft",
        "skill": "Skill",
        "skillRank": "Level",
        "manHour": "Hours",
        "num": "No."
    },
    "CraftCostPage": {
        "title": "Manpower Cost",
        "craft": "Craft",
        "employee": "Staff",
        "startTime": "Start Time",
        "endTime": "End Time",
        "manHour": "Actual Man-hours",
        "manHourMustRequired": "Actual Man-hours (At least to fill one item)",
        "overtimeFlag": "Overtime",
        "workOrder": "WO",
        "skill": "Skill",
        "skillRank": "Level"
    },
    "PlanAssignPage": {
        "title": "Staff Assignment",
        "craft": "Craft",
        "employee": "Staff",
        "employeeTime": "Time"
    },
    "MaterialCostPage": {
        "title": "Material Cost",
        "material": "Material",
        "planNum": "Plan Qty.",
        "num": "Actual Quantity",
        "warehouse": "Warehouse"
    },
    "ToolCostPage": {
        "title": "Tools Cost",
        "material": "Tools",
        "planNum": "Plan Qty.",
        "num": "Actual Quantity",
        "warehouse": "Warehouse",
        "planManHour": "Planned Man-hours",
        "manHour": "Actual Man-hours"
    },
    "TaskMeasurePage": {
        "title": "Measurement",
        "measurePoint": "Point",
        "asset": "Equipment",
        "location": "Location",
        "measureValue": "Value",
        "requireAssetOrLocation": "Equipment / Location",
        "measureTime": "Time",
        "measureUnit": "Unit",
        "measureType": "Type",
        "upperThanMeasuredValue": "The measured value exceeds the upper limit of the measuring point",
        "lowerThanMeasuredValue": "The measured value is lower than the lower limit of the measuring point"
    },
    "FollowUpPage": {
        "title": "Follow-Up Status",
        "jobPlan": "Job Plan",
        "targetStartTime": "Target Start",
        "targetEndTime": "Target Finish",
        "predictStartTime": "Scheduled Start",
        "predictEndTime": "Scheduled Finish",
        "actualStartTime": "Actual Start",
        "actualEndTime": "Actual Finish",
        "haltMinute": "Downtime",
        "remark": "Reporting"
    },
    "CraftCostListPage": {
        "title": "Manpower Cost",
        "employee": "Staff",
        "craft": "Craft",
        "skill": "Skill",
        "skillRank": "Level",
        "startTime": "Start Time",
        "endTime": "End Time",
        "manHour": "Act. Hour",
        "manHour2": "Hours",
        "manHourType": "Type",
        "overtimeFlag": "Overtime",
        "action": "Ops.",
        "yesFlag": "Yes",
        "noFlag": "No",
        "confirmDelete": "Delete?",
        "deleteSuccess": "Deleted successfully",
        "workOrder": "WO",
        "workOrderDescription": "Description",
        "manHourCount": "Normal time: ",
        "overtimeManHourCount": "Overtime:"
    },
    "WorkOrderDetailPage": {
        "title": "Work Order Details",
        "confirmDelete": "Delete?",
        "deleteSuccess": "Deleted successfully",
        "changeStatus": "CHG STATUS",
        "changeStatusSuccess": "Status successfully changed",
        "basicData": "Basic Info.",
        "billCode": "Work Order: ",
        "referCode": "Reference: ",
        "submitter": "Report By: ",
        "priority": "Priority: ",
        "asset": "Equipment: ",
        "assetLocation": "Location: ",
        "location": "Location: ",
        "workOrderStatus": "Status: ",
        "workOrderstatus2": "Status",
        "workOrderType": "Work Type: ",
        "description": "Description: ",
        "followUp": "Follow-Up Status",
        "jobPlan": "Job Plan: ",
        "targetStartTime": "Target Start: ",
        "targetEndTime": "Target Finish: ",
        "predictStartTime": "Scheduled Start: ",
        "predictEndTime": "Scheduled Finish: ",
        "actualStartTime": "Actual Start: ",
        "actualEndTime": "Actual Finish: ",
        "haltMinute": "Downtime: ",
        "remark": "Reporting: ",
        "remark2": "Remark",
        "task": "Task",
        "taskCode": "No.",
        "taskName": "Description",
        "taskFinishFlag": "Approved?",
        "planAssign": "Staff Assignment",
        "planCraftCost": "Planned Manpower",
        "craftCost": "Manpower Cost",
        "employee": "Staff",
        "craft": "Craft",
        "employeeTime": "Time",
        "skill": "Skill",
        "skillRank": "Level",
        "manHour": "Act. Hour",
        "manHour2": "Hours",
        "manHourType": "Type",
        "materialCost": "Material Cost",
        "toolCost": "Tools Cost",
        "material": "MATL",
        "material2": "Tools",
        "planNum": "Plan Qty.",
        "num": "Act. Qty.",
        "numOfPeople": "No.",
        "planManHour": "Planned Man-hours",
        "warehouse": "Warehouse",
        "taskMeasure": "Measurement",
        "asset1": "Equip.",
        "location1": "Location",
        "measureValue": "Value",
        "measurePoint": "Point",
        "measureTime": "Time",
        "measureUnit": "Unit",
        "measureType": "Type",
        "hazard": "Hazards and Precautions",
        "hazardType": "Hazard",
        "hazardRemedy": "Precaution",
        "action": "Ops.",
        "faultRelation": "Failure Information",
        "faultType": "Class: ",
        "faultIssue": "Problem: ",
        "faultCause": "Cause: ",
        "faultRemedy": "Remedy: ",
        "billDate": "Reported: ",
        "createdTime": "Created: ",
        "statusLog": "Status Change Record",
        "beforeStatus": "Previous Status",
        "afterStatus": "Subsequent Status",
        "statusLogRemark": "Remark",
        "statusLogCreatedBy": "Status Changed by",
        "statusLogCreatedTime": "Status Changing Time"
    },
    "MaterialRequestFormArrivalListPage": {
        "title": "Prepare Deliveries",
        "confirmArrival": "Materials ready for delivery?",
        "arrivalSuccess": "Deliveries prepared successful!",
        "project": "Project",
        "material": "MATL",
        "workOrder": "WO",
        "num": "App. Qty",
        "waitNum": "Pend. Qty",
        "arrivalNum": "Del. Qty",
        "inputPlaceholder": "Please Input",
        "confirmArrival2": "Confirm Deliveries",
        "search": "Search",
        "applyBillCode": "Requisition No.",
        "materialCode": "Material",
        "workOrderBillCode": "Work Order No."
    },
    "MaterialRequestFormArrivalPage": {
        "title": "Deliveries List",
        "project": "Project",
        "confirmRecive": "Confirm Receive?",
        "confirmRecive2": "Receive",
        "receiveSuccess": "Receipt successful!",
        "search": "Search",
        "applyBillCode": "REQ",
        "materialCode": "MATL",
        "workOrderBillCode": "WO",
        "inputPlaceholder": "Please Input",
        "back": "Back",
        "material": "Materials",
        "materialApply": "REQ",
        "createdBy": "Req. by",
        "arrivalNum": "Del. Qty.",
        "receiveNum": "Rec. Qty.",
        "receiveDate": "Received",
        "receiverBy": "Rec. by",
        "note": "Remark",
        "temporarily": "Process later",
        "waiting": "To Be Received",
        "waiting2": "Pending To Receive",
        "completed": "Received",
        "completed2": "Collected"
    },
    "NoticeListPage": {
        "title": "Announcements",
        "billCode": "Ref. No.: ",
        "noticeTitle": "Subject: ",
        "content": "Content: ",
        "noticeType": "Category: ",
        "sendTime": "Issue: ",
        "noticeType2": "Category",
        "search": "Search"
    },
    "NoticeDetailPage": {
        "title": "Announcement Details",
        "basicData": "Basic Information",
        "billCode": "Ref. No.: ",
        "noticeTitle": "Subject: ",
        "status": "Status: ",
        "noticeType": "Category: ",
        "sendTime": "Issued: ",
        "billDate": "Created: "
    },
    "NOTICE_STATUS": {
        "E": "Editing",
        "P": "Issued",
        "C": "Recalled"
    },
    "SuggestionPage": {
        "title": "Suggestions",
        "organization": "Company",
        "project": "Project",
        "suggestionType": "Category",
        "content": "Content",
        "submitWithError": "Suggestion was submitted successfully, but the media files may be lost!"
    },
    "SuggestionListPage": {
        "title": "Suggestion Box",
        "organization": "Company: ",
        "project": "Project: ",
        "submited": "Submitted",
        "replied": "Replied",
        "recalled": "Recalled",
        "billCode": "Ref. No.: ",
        "suggestionType": "Category: ",
        "content": "Content: ",
        "recall": "Recall",
        "edit": "Edit",
        "confirmRecall": "Recall?",
        "recallSuccess": "Recalled successfully"
    },
    "SuggestionDetailPage": {
        "title": "Suggestion Details",
        "basicData": "Basic Information",
        "billCode": "Code: ",
        "status": "Status: ",
        "content": "Content: ",
        "organization": "Company: ",
        "project": "Project: ",
        "suggestionType": "Type: ",
        "billDate": "Issued: ",
        "createdTime": "Created: ",
        "reply": "Reply",
        "repliedBy": "By: ",
        "repliedcontent": "Content: ",
        "repliedTime": "Date: "
    },
    "FaultRelationPage": {
        "title": "Failure Information",
        "faultType": "Failure Class",
        "faultIssue": "Problem",
        "faultCause": "Cause",
        "faultRemedy": "Remedy"
    },
    "AccountPage": {
        "title": "My Profile",
        "username": "Username: ",
        "employeeNo": "Staff No.: ",
        "clientNo": "Code: ",
        "preferredLanguage": "Language: ",
        "language": "Change Language",
        "version": "Version: ",
        "logout": "Logout"
    },
    "ApprovalPage": {
        "title": "Approve  Shift Changing Application",
        "attdOrg": "Group: ",
        "employeeName": "Staff Name: ",
        "reason": "Reason: ",
        "startDate": "Start Date: ",
        "endDate": "End Date: ",
        "originalOfficeHour": "Current Shift Type: ",
        "newOfficeHour": "Intended Shift: ",
        "status": "Status: ",
        "confirmPass": "Confirm?",
        "confirmNoPass": "Confirm to reject the application?",
        "confirmRevoke": "Confirm to revoke the application?",
        "agree": "Approve",
        "disagree": "Reject",
        "revoke": "Revoke"
    },
    "InboxPage": {
        "title": "Notification Center",
        "readAllMsg": "將所有消息標為已讀？",
        "readNumberMsg": "{0} 條消息標為已讀"
    },
    "InboxDetailPage": {
        "title": "Notification",
        "followUp": "View details"
    },
    "SearchPage": {
        "title": "Search"
    },
    "AnnualLeave": {
        "title": "Annual Leave Extension Application",
        "applicationNo": "Application Code",
        "company": "Company",
        "department": "Department",
        "employee": "Staff",
        "holidayType": "Leave Group",
        "daysClears": "Annual Leave Clearance Type",
        "daysNumbers": "Required for Extension (days)",
        "holidayPlan": "Tentative Leave Plan",
        "approvalStatus": "Approval Status",
        "END_OF_MARCH": "March",
        "END_OF_DECEMBER": "December",
        "startDate": "Start Date",
        "startPeriod": "Start Date",
        "endDate": "End Date",
        "endPeriod": "End time",
        "days": "No of Day",
        "remark": "Remark",
        "leaveDays": "No. of day(s)",
        "clearDays": "可清天數",
        "maxDays": "不能大於可清天數最大值{0}",
        "followUp": "Review",
        "createdBy": "Initiator",
        "approvalTime": "Approval Time",
        "status": "Approval Status"
    },
    "Exter": {
        "colon": ":"
    }
}
