export default {
    M7_Title: "申報房屋稅M/7",
    M7_Address: "房屋紀錄編號/地址",
    M7_ReportYear: "申報年度",
    M7_OwnerName: "業主姓名",
    M7_ConnectInfo: "聯絡資料",
    M7_Email: "電郵地址",
    M7_Email_Lang: "訊息語言",
    M7_To_Submit: "預覽遞交",
    M7_Tag: "如欲接收本局有關房屋稅事宜的短訊或電郵，請填寫。",
    M7_Property: "物業管理費用（全年）",
    M7_Building_Maintenance: "大廈維修費用",
    M7_Ohters: "其他費用",
    M7_Total: "總數",
    M7_MUST_input: "請填寫 %{name} 物業管理費用（全年）或大廈維修費用",
    M7_MUST_input2: "請填寫 %{name} 物業管理費用（全年）",
    M7_MUST_input3: "請填寫 %{name} 大廈管理費用",
    M7_MUST_input4: "請填寫 %{name} 其他費用的補充說明",
    M7_MUST_input5: "請填寫 %{name} 其他費用",
    M7_Remark_ext: "補充說明",
    Reload: "重新載入",
    Report_notSubmit_tip: "當前未在申報期不可申報",

    M5_Title: `職業稅M/5收益申報書`,
    M5_GROUP: `組別`,
    M5_ReportValue: `申報內容 (可多選)`,
    M5_First_Group: `第一組（受僱他人）`,
    M5_Second_Group: `第二組（自僱）`,
    M5_Phone: `聯絡電話`,
    M5_Increate: `收益紀錄%{index}`,
    M5_number: `檔案或僱主編號`,
    M5_name: `僱主名稱`,
    M5_tag1: `總金錢收益`,
    M5_tag2: `不屬課稅收益`,
    M5_tag3: `已繳稅款`,
    M5_tag4: `總額-已繳稅款`,
    M5_code: `業務代號`,
    M5_work_name: `業務名稱`,
    M5_get: `收益`,
    M5_lost: `業務負擔`,
    M5_have: `有`,
    M5_no: `沒有`,
    M5_tick: `開支單據`,
    M5_tick_m7: `M/7收據`,
    M5_submit_tag: `APP申報M/5只適用於下列情況：\n1.平常年度申報 \n2.沒有非金錢收益 \n3.不具備編製會計\n4.不具備會計冊簿\n
請於法定申報期內前往財政局補交M/7收據及開支單據。`,
    M5_total: `總計`,
    M5_total_increate: `總業務收益`,
    M5_total_lost: `總業務負擔`,
    M5_total_loss: `損益`,
    M5_add_increate: `新增收益明細`,
    Report_download_file: `下載申報文件`,
}